lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - conf/igenomes.config
    - conf/igenomes_ignored.config
nf_core_version: 3.2.1
repository_type: pipeline
template:
  author: Martin Proks, Annick Renevey
  description: Nextflow rnafusion analysis pipeline, part of the nf-core community.
  force: false
  is_nfcore: true
  name: rnafusion
  org: nf-core
  outdir: .
  version: 4.0.0dev
